site:
  title: Documentation project
  url: http://127.0.0.1:8080
  start_page: pet-project::index.adoc
content:
  sources:
    - url: https://github.com/antontuhai/documentation.git
      branches: master
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true