site:
  title: My Antora Demo Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://antora.gitlab.io/demo/docs-site
  start_page: test-welcome-page::index.adoc
#git:
#  plugins:
#    http: ./runner/git-plugin-http.js
content:
  sources:
  - url: https://github.com/antontuhai/documentation.git
    branches: master
    start_path: documentation
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
